### ISSUE TITLE
I encountered a little bug.

### ISSUE THREAD

**Issue by HowToPlayMeow** [NotnHeavy/TF2-Attribute-Manager#2]
**"mod see enemy health"** There is a slight bug. I can't see the player's name.

I used it instead of **"Plugin Aim Names"** because AimNames was having issues on my server.

![bug](https://github.com/NotnHeavy/TF2-Attribute-Manager/assets/124129630/04cd2804-84e9-47dd-874e-543206bd4312)

	"scout"
	{
		"mod see enemy health"							"1"
	}
	"soldier"
	{
		"mod see enemy health"							"1"
	}
	"pyro"
	{
		"mod see enemy health"							"1"
	}
	"demoman"
	{
		"mod see enemy health"							"1"
	}
	"heavy"
	{
		"mod see enemy health"							"1"
	}
	"engineer"
	{
		"mod see enemy health"							"1"
	}
	"medic"
	{
		"mod see enemy health"							"1"
	}
	"sniper"
	{
		"mod see enemy health"							"1"
	}

**Comment by NotnHeavy** [comment]
I think that's just a limitation with this attribute, unfortunately; see more here:
https://forums.alliedmods.net/archive/index.php/t-327568.html

**Comment by HowToPlayMeow** [comment]
Thank you @NotnHeavy :3
![image](https://github.com/NotnHeavy/TF2-Attribute-Manager/assets/124129630/2aaf73eb-dc7d-44e7-8e68-78f227a2d016)

**Comment by HowToPlayMeow** [comment]
I have installed the **Plugin** [**SM-TFShowEnemyInfo**](https://github.com/nosoop/SM-TFShowEnemyInfo/blob/sync-hud/scripting/tf_show_enemy_info.sp)
But it doesn't work. Or did I install it wrong?

**Comment by NotnHeavy** [comment]
I think that looks like a plugin that exposes a forward that's up to the programmer to manipulate.

**Comment by NotnHeavy** [comment]
I mean, I'm not really sure how - I just took a quick breeze and I'm honestly not focusing much on SourceMod plugin development at the moment. I suppose you could try asking in the AlliedModders Discord server though>?
